name: Action Sample

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: ログレベル
        default: warning
      tags:

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Workflow Dispatch
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
      # Python バージョンチェック
      - name: Get Python version
        run: |
          python -V
          pip -V

      # pipで環境構築
      - name: Install dependencies
        run: pip install -r requirements.txt

      # テストコードの実行
      - name: Run Python
        run: python python-sample.py